Scripts to prepare kb
ostis-dev/ostis-web-platform pull request #10
Opened 2021-04-10 06:38 UTC by Vikort

Added scripts to prepare and fix kb
Updated kb repo link

2021-04-12 15:59 UTC, ValikVityaz requested changes

2021-04-12 15:59 UTC, ValikVityaz commented on scripts/copy_kb.py
> +        print(er)
```suggestion
    except (FileNotFoundError, OSError) as er:
        print(er)
```

2021-04-12 15:59 UTC, ValikVityaz commented on scripts/prepare_kb.py
> +    CopyKbPaths.KB_COPY = os.path.join(CopyKbPaths.OSTIS.value, copy_kb_path)
`CopyKbPaths.KB_COPY` will have `CopyKbPaths.OSTIS.value` twice in its path. It should be just set equal to `copy_kb_path` if we need to save this path in `CopyKbPaths.KB_COPY`.
```suggestion
    CopyKbPaths.KB_COPY = copy_kb_path
```

2021-04-12 15:59 UTC, ValikVityaz commented on scripts/remove_scsi.py
> +                            tabulation_string = tabulation_string + " "
```suggestion
                        tabulation_string = " " * len(edit_line_list[0])
```

2021-04-12 15:59 UTC, ValikVityaz commented on scripts/remove_scsi.py
> +                        buffer_file_list.append("*];;")
```suggestion
                        buffer_file_list.append("*];;\n")
```

2021-04-12 15:59 UTC, ValikVityaz commented on scripts/remove_scsi.py
> +                                relative_path = scsi_path_list[i] + '/'
Here it should be `relative_path += scsi_path_list[i] + '/'`, but there is even an easier way to write it
```suggestion
                        if scsi_path.rfind('/') >= 0:
                            relative_path = scsi_path[:scsi_path.rfind('/') + 1]
```

2021-04-12 15:59 UTC, ValikVityaz commented on scripts/remove_scsi.py
> +                    if scs_file_line.find('[*^"file://') >= 0:
Is it possible for multiple `scsi` file links to be on the same line? If so, this won't work for all of them.

2021-04-23 09:59 UTC, ValikVityaz approved these changes

2021-07-19 14:18 UTC, KovalM requested changes

2021-07-19 14:18 UTC, KovalM commented on scripts/prepare.sh
> +clone_project https://github.com/ostis-dev/ims.ostis.kb.git ims.ostis.kb master
Insert last commit hash after merge https://github.com/ostis-dev/ims.ostis.kb/pull/97 instead of master

2021-07-19 14:18 UTC, KovalM commented on scripts/copy_kb.py
> +import os
Create folder kb_scripts and move this scripts to this folder

2021-07-19 14:18 UTC, KovalM commented on scripts/prepare_kb.py
> +import os
Move this scripts to kb_scripts folder

2021-07-19 14:18 UTC, KovalM commented on scripts/prepare_kb.py
> +    scripts = [os.path.join(CopyKbPaths.SCRIPTS.value, 'remove_scsi.py')]
move this list to constants

2021-07-19 14:18 UTC, KovalM commented on scripts/prepare_kb.py
> +    if len(sys.argv) == 2:
create default arg as prepared_kb folder at the root

2021-07-19 14:18 UTC, KovalM commented on scripts/prepare_kb.py
> +import os
This script should be called in build_kb.sh if your pass to this script key "-p".
build_kb.sh should process prepared kb

2021-07-22 12:04 UTC, KovalM reviewed
Add prepared_kb to .gitignore

2021-07-26 07:49 UTC, KovalM approved these changes

2021-07-26 18:13 UTC, merged