Add gwf to scs scripts
ostis-dev/ostis-web-platform pull request #14
Opened 2021-08-19 15:51 UTC by Vikort

2021-09-02 14:03 UTC, ValikVityaz commented on scripts/kb_scripts/scs_writer.py
> +      if not idtf.startswith("_"):
why isn't the same check/correction done for a constant node with an identifier starting with '_'?

2021-09-02 14:03 UTC, ValikVityaz commented on scripts/kb_scripts/scs_writer.py
> +            msg = "Edge type `{}` is not supported. Please add it into EdgeTypes or into UnsupportedEdgeTypes".format(edge_type)
```suggestion
            msg = "Edge type `{}` is unknown. Please add it into EdgeTypes or into UnsupportedEdgeTypes".format(edge_type)
```

2021-09-02 14:55 UTC, ValikVityaz commented on scripts/kb_scripts/scs_writer.py
> +      self.log_error("Wasn't able to create edges: {}".format(edge_ids))
It would be better to specify exactly which edges couldn't be processed.

2021-09-21 15:19 UTC, ValikVityaz approved these changes

2021-09-21 15:53 UTC, Zioba approved these changes

2021-09-28 08:51 UTC, KovalM requested changes

2021-09-28 08:51 UTC, KovalM commented on scripts/kb_scripts/gwf_to_scs.py
> +from gwf_parser import GWFParser
Move GWF parser and SCsWriter to separate folder in kb_scripts as support scripts. In kb_scripts should be only main scripts for prepare KB

2021-09-28 08:51 UTC, KovalM commented on scripts/kb_scripts/prepare_kb.py
> +            prepared_repo_path.write(os.path.join(os.path.split(copy_kb_path)[1], 'converted'))
We already have prepared_kb filder in the root of ostis-web-platform. Why we need converted folder?

2021-09-30 13:48 UTC, KovalM approved these changes

2021-09-30 14:19 UTC, merged