feat(build): improve kb paths usability
ostis-dev/ostis-web-platform pull request #16
Opened 2021-10-19 15:18 UTC by NikitaZotov

Changes:
- implemented splitting repo.path check that it is not worth checking checked directories;
- removed the dependency of checkers from scripts from prepare_kb;
- introduced paths universality in preparing process.

2021-10-20 13:41 UTC, NikiforovSergei approved these changes

2021-10-20 14:32 UTC, KovalM requested changes

2021-10-20 14:32 UTC, KovalM commented on scripts/kb_scripts/prepare_kb.py
> +        main(sys.argv[1], sys.argv[2], sys.argv[3])
We will get here in case when len(sys.argv) == 2, as result, no value for sys.argv[3]

2021-10-20 14:32 UTC, KovalM commented on scripts/kb_scripts/prepare_kb.py
> +    VERIFY = '#verify'
Use Prepare concept

2021-10-20 14:32 UTC, KovalM commented on scripts/kb_scripts/gwf_to_scs.py
> +  args.output =os.path.join(args.kb_path, 'converted_gwf_to_scs')
.scs files from .gwf should be placed near sources .scs file, not in separate folder

2021-10-20 14:32 UTC, KovalM commented on scripts/kb_scripts/gwf_to_scs.py
> +  parser.add_argument('repo_path', action='store',
Remove using this arg

2021-10-21 09:07 UTC, KovalM approved these changes

2021-10-21 10:28 UTC, merged

2021-10-25 08:47 UTC, NikitaZotov commented
Problem had been resolved