Add ability to import monography
ostis-dev/ostis-web-platform pull request #20
Opened 2021-12-07 09:57 UTC by SHtress

2021-12-13 11:18 UTC, Vikort approved these changes

2021-12-14 08:58 UTC, KovalM requested changes

2021-12-14 08:58 UTC, KovalM commented on scripts/prepare.sh
> +clone_monography=0
```suggestion
clone_standard=0
```

2021-12-14 08:58 UTC, KovalM commented on scripts/prepare.sh
> +			clone_monography=1
```suggestion
		"clone_standard" )
			clone_standard=1
```

2021-12-14 08:58 UTC, KovalM commented on scripts/prepare.sh
> +	clone_project git@github.com:semsystems/monography2020.git monography2020 tex2sc
```suggestion
	clone_project git@github.com:semsystems/monography2020.git ostis-standard tex2sc
```

2021-12-14 08:58 UTC, KovalM commented on scripts/prepare.sh
> +monography_path="monography2020/translated_scs"
```suggestion
standard_path="monography2020/translated_scs"
```

2021-12-14 08:58 UTC, KovalM commented on scripts/prepare.sh
> +	clone_project git@github.com:semsystems/monography2020.git monography2020 tex2sc
Move content of this "if" to separate script

2021-12-14 08:58 UTC, KovalM commented on scripts/prepare.sh
> +		echo $monography_path >> ../repo.path
```suggestion
	if ! grep -q $standard_path ../repo.path ; then
		echo "#standard" >> ../repo.path 
		echo $standard_path >> ../repo.path
```

2021-12-14 08:58 UTC, KovalM commented on scripts/prepare.sh
> +	clone_project git@github.com:semsystems/monography2020.git monography2020 tex2sc
tex2sc branch should be replaced by commit hash from master branch after merge pr from monography repo

2021-12-20 10:46 UTC, KovalM requested changes

2021-12-20 10:46 UTC, KovalM commented on scripts/clone_standart.sh
> +clone_project git@github.com:semsystems/monography2020.git ostis-standart tex2sc
Repo was renamed and moved to another org. Update ssh

2022-03-12 07:14 UTC, closed without merging