feat(scripts): added new script for dump saving
ostis-dev/ostis-web-platform pull request #7
Opened 2021-04-02 11:06 UTC by lexfor

Added new script for copy segments.scdb file with time and date

2021-04-03 11:38 UTC, ShunkevichDV approved these changes
Need testing in real environment

2021-04-03 11:38 UTC, ShunkevichDV commented on scripts/dump_saver.bash
> +echo "programm start..."
program

2021-04-03 11:38 UTC, ShunkevichDV commented on scripts/dump_saver.bash
> +echo "sc-web.ini path: "$file
Filename may be different

2021-04-05 08:32 UTC, MikhailSadovsky requested changes

2021-04-05 08:32 UTC, MikhailSadovsky commented on scripts/dump_saver.bash
> +echo "programm start..."
Rename script extension to `.sh`

2021-04-05 08:32 UTC, MikhailSadovsky commented on scripts/dump_saver.bash
> +echo "programm start..."
Add `#!/bin/bash` as a first line

2021-04-05 08:32 UTC, MikhailSadovsky commented on scripts/dump_saver.bash
> +echo "programm start..."
Rename message as it's not a program. Smth like "script for saving dumps starts.."

2021-04-05 08:32 UTC, MikhailSadovsky commented on scripts/dump_saver.bash
> +echo "programm start..."
Rename message as it's not a program. Smth like "script for saving dumps starts.."

2021-04-05 08:32 UTC, MikhailSadovsky commented on scripts/dump_saver.bash
> +echo "wait new dump"
```suggestion
echo "waiting for a new dump"
```

2021-04-05 08:32 UTC, MikhailSadovsky commented on scripts/dump_saver.bash
> +       echo "wait new dump"
```suggestion
       echo "waiting for a new dump"
```

2021-04-05 08:32 UTC, MikhailSadovsky commented on scripts/dump_saver.bash
> +   sleep 5
Could you please explain why we need `sleep` here and why 5 exactly

2021-04-05 08:32 UTC, MikhailSadovsky commented on scripts/dump_saver.bash
> +done
```suggestion
done

```

2021-04-05 11:50 UTC, MikhailSadovsky approved these changes

2021-04-07 08:27 UTC, merged